site_name: UIU Management System
site_url: https://uiu-ms.web.app/
nav:
    - Home: index.md
    - Installation Process: installation.md
    - User GuideLines : guideline.md
    - Demo Information : demoinfo.md
    - Testing : testing.md
    - API Reference : api.md

theme: readthedocs
