site_name: UIU Management System
site_url: https://saif-tasnim.github.io/UIU-MS-Docs/
nav:
    - Home: index.md
    - Installation Process: installation.md
    - User GuideLines : guideline.md
    - Demo Information : demoinfo.md
    - Testing : testing.md
    - API Reference : api.md

theme: readthedocs
